# Generated by Django 3.2.4 on 2021-06-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanpage',
            name='subject',
            field=models.CharField(default='No Subject', max_length=150),
            preserve_default=False,
        ),
    ]
